### DISCUSSION TITLE
Passing application parameters an array

### DISCUSSION THREAD

**Discussion by davidt-gh** [argoproj-labs/argocd-operator#1534] [Q&A]
Our current installation is tenant for each member, the tenant include backend chart and frontend chart.
I'm using argocd application with `sources` instead `source` to deploy both together for each tenant.
To make some additional changes for some tenants, we want to change environment variables of the deployment.
Current method allow to pass parameter which overwrite a value from values, but in my case I have in `values.yaml`:
```
env:
  - name: TEST
     value: "OK"
  - name: TZ
     value: "America/New-York"
```

and in my deployment I'm quote this part.
How I can add or overwrite this section from `Application` ( argoproj.io/v1alpha1 )
