### DISCUSSION TITLE
ArgoCD Ingress TLS | Cert-manager | ClusterIssuer not working

### DISCUSSION THREAD

**Discussion by bitvijays** [argoproj-labs/argocd-operator#603] [Q&A]
Dear ArgoCD Operator Team and the community,

Hope everyone is doing well. Thank you for the awesome work on the ArgoCD operator. We really appreciate it; it helps us to make our life easier. Thank you :).

We are trying to deploy ArgoCD on a Kubernetes Cluster. Cluster already has cert-manager (cluster-issuer) and Nginx ingress controller. However, when the certificate is issued, it is from ` Kubernetes Ingress Controller Fake Certificate` rather than the cluster-issuer. We did test if our `cluster-issuer` is issuing certificates or not, and it does. We are unsure what is wrong or how to debug it; some guidance would be appreciated. Thank you :)

Here is our `yaml` file

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
  oidcConfig: |
    name: Keycloak
    issuer: https://keycloak.bitvijays.local/auth/realms/bitvijays.local
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer-4    
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        kubernetes.io/tls-acme: "true"
    host: argocd.bitvijays.local
    insecure: true  

```

Hey @iam-veeramalla Hope you are doing well. Thank you for your awesome work on the ArgoCD Operator. Could you please have a look at this? or maybe refer who might help on this?
