### DISCUSSION TITLE
Getting ExcludedResourceWarning - Unable to utilize sourceNamespace feature for Operator v0.5.0

### DISCUSSION THREAD

**Discussion by KevinBonilla** [argoproj-labs/argocd-operator#846] [Q&A]
Hi Argo-nauts!

I've been trying to utilize the beta feature introduced in 0.5.0 following these resources:

Original PR: https://github.com/argoproj-labs/argocd-operator/pull/794
Documentation reference for apps in any namespace: https://argocd-operator.readthedocs.io/en/latest/usage/apps-in-any-namespace/
ResourceInclusion/Exclusion relevant links: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion
https://stackoverflow.com/questions/72398093/argo-cd-trying-to-deploy-app-using-app-of-apps-pattern-warning-excludedres
https://github.com/argoproj/argo-cd/discussions/8674

Originally I was getting `ComparisonErrors` which made me implement `spec.server.resourceInclusions` rules. My config looks like so. For context I'm including all resources `kinds` for apiGroup `argoproj.io/v1alpha1` :
```
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  sso:
    provider: dex
    dex:
      config: |
        connectors:
        - type: microsoft
          id: microsoft
          name: Azure
          config:
            clientID: <Azure client ID>
            clientSecret: $<argocd-dex-secret>
            redirectURI: https://<argo URL>/api/dex/callback
            tenant: <omitted>
  rbac:
    defaultPolicy: "role:readonly"
    policy: g, <Azure Group>, role:admin
    scopes: "[groups]"
  tls:
    ca:
      secretName: argocd-tls
  server:
    autoscale:
      enabled: false
      hpa:
        maxReplicas: 3
        minReplicas: 1
        scaleTargetRef:
          apiVersion: extensions/v1beta1
          kind: Deployment
          name: argocd-server
        targetCPUUtilizationPercentage: 50
    host: <argo URL>
    insecure: true
    replicas: 1
    resources: {}
    service:
      type: ClusterIP
  sourceNamespaces:
    - argocd
    - dev
  resourceExclusions: |
    - apiGroups:
      - constraints.gatekeeper.sh/v1beta1
      kinds:
      - "*"
      clusters:
      - "*"
  resourceInclusions: |
    - apiGroups:
      - "argoproj.io/v1alpha1"
      kinds:
      - "*"
      clusters:
      - "*"  
```

Role/rolebindings are being created via SourceNamespaces:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-01-23T21:34:11Z"
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
  name: argocd_dev
  namespace: dev
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - Secret
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocds.argoproj.io/name: argocd
    argocds.argoproj.io/namespace: argocd
  creationTimestamp: "2023-01-23T15:05:08Z"
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd_dev
    app.kubernetes.io/part-of: argocd
  name: argocd_dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd_dev
subjects:
- kind: ServiceAccount
  name: argocd-argocd-server
  namespace: argocd
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: argocd
```

Even the namespace `dev` includes the proper labels so argo should be able to manage the namespace.
```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-09-29T16:24:02Z"
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/managed-by-cluster-argocd: argocd
    kubernetes.io/metadata.name: dev
  name: dev
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

My test application is able to sync but I get 5 app condition warnings.
```
ExcludedResourceWarning
Resource /ConfigMap spring-github-actions-config is excluded in the settings
an hour ago (Wed Jan 25 2023 10:20:53 GMT-0500)
ExcludedResourceWarning
Resource /Secret secret-spring-github-actions is excluded in the settings
a few seconds ago (Wed Jan 25 2023 11:25:03 GMT-0500)
ExcludedResourceWarning
Resource /Service spring-github-actions is excluded in the settings
a few seconds ago (Wed Jan 25 2023 11:25:03 GMT-0500)
ExcludedResourceWarning
Resource apps/Deployment spring-github-actions is excluded in the settings
a few seconds ago (Wed Jan 25 2023 11:25:03 GMT-0500)
ExcludedResourceWarning
Resource networking.istio.io/VirtualService spring-github-actions is excluded in the settings
a few seconds ago (Wed Jan 25 2023 11:25:03 GMT-0500)
```

My questions are how do I include the resources of the application? I thought that would be done with `resourcecInclusions` apiGroup `argoproj.io/v1alpha1`? How do I "include" the application in Argo? I've been stuck on this for some time now and came here as a last resort, really appreciate any help.
