### DISCUSSION TITLE
Wish to ristrict all github repo but enable specific repo, how to please

### DISCUSSION THREAD

**Discussion by iamraj007** [argoproj-labs/argocd-operator#889] [Q&A]
So in ArgoCD : **AppProject** i am trying to restrict sourceRepo that will restrict all repo excluded one specific repo(URL of repo)..so its kind of wild card won't work..

Example below AppProject wish to disable all github repo but allow a specif user repo/specif repo (though this won't work..)
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
  name: proj-devns
  namespace: argocd
spec:
  sourceRepos:
  - '!https://github.com/**'
  - '!https://github.com/*/*'
  - https://github.com/iamraj007/argo_apps.git
```

Any suggestion to make it work will be appreciated.
