### ISSUE TITLE
.spec.sso.dex.openShiftOAuth: true no longer seems to work

### ISSUE THREAD

**Issue by bergner** [argoproj-labs/argocd-operator#1012]
**Describe the bug**

Setting `.spec.sso.dex.openShiftOAuth: true` in the ArgoCD CR causes the "Log in via Openshift" button to appear in ArgoCD's UI but clicking that button causes a 400 error on `GET https://argocd-server-argocd.apps-crc.testing/auth/login?return_url=https://argocd-server-argocd.apps-crc.testing/applications` with the message:

````
Invalid redirect URL: the protocol and host (including port) must match and the path must be within allowed URLs if provided
````

**To Reproduce**

I have been running ArgoCD on Openshift CRC successfully for a couple of months now but I recently redid my Openshift CRC setup from scratch to increase its dedicated disk size. After installing ArgoCD operator through OperatorHub interface in Openshift I created an "argocd" namespace with `oc create ns argocd` and then provisioned an ArgoCD CR with `oc apply -f` on the following:

````
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
users:
- kubeadmin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: cluster-admins
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 20m
        memory: 128Mi
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  resourceTrackingMethod: annotation
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 25m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
    provider: dex
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'
  repo:
    resources:
      limits:
        cpu: 25m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 256Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 25m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 25m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: 50m
        memory: 2Gi
      requests:
        cpu: 20m
        memory: 1Gi
    sharding: {}
````

I also tried adding `.spec.server.url: https://argocd-server-argocd.apps-crc.testing` in the ArgoCD CR but that did not help.

**Additional information**

The `argocd-cm` ConfigMap contains this (plus some other properties that I don't think are related to this):

````
data:
  dex.config: |
    connectors:
    - config:
        clientID: system:serviceaccount:argocd:argocd-argocd-dex-server
        clientSecret: $oidc.dex.clientSecret
        groups: []
        insecureCA: true
        issuer: https://kubernetes.default.svc
        redirectURI: https://argocd-server/api/dex/callback
      id: openshift
      name: OpenShift
      type: openshift
  url: https://argocd-server
````

The `argocd-argocd-dex-server` ServiceAccount has the following annotation:

````
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.argocd: https://argocd-server/api/dex/callback
````

Unfortunately I don't have the exact contents of `argocd-cm` and `argocd-argocd-dex-server` from before the reinstall of Openshift CRC but at least one theory is that it used to use the Route FQDN and not use "https://argocd-server".

I tried setting `--loglevel debug` on both the argocd-server and argocd-dex-server Deployments. I can't see what is happening when I click "Log in via Openshift" but on startup of argocd-dex-server this entry in the log file is interesting (I replaced "\n" with line breaks here for readability). Why is `config.redirectURI` and `staticClients[0].redirectURIs` completely different for example?

````
time="2023-10-01T13:05:13Z" level=debug msg="
connectors:
- config:
    clientID: system:serviceaccount:argocd:argocd-argocd-dex-server
    clientSecret: '********'
    groups: []
    insecureCA: true
    issuer: https://kubernetes.default.svc
    redirectURI: https://argocd-server/api/dex/callback
  id: openshift
  name: OpenShift
  type: openshift
grpc:
  addr: 0.0.0.0:5557
issuer: https://argocd-server/api/dex
oauth2:
  skipApprovalScreen: true
staticClients:
- id: argo-cd
  name: Argo CD
  redirectURIs:
  - https://argocd-server/auth/callback
  secret: '********'
- id: argo-cd-cli
  name: Argo CD CLI
  public: true
  redirectURIs:
  - http://localhost
  - http://localhost:8085/auth/callback
storage:
  type: memory
telemetry:
  http: 0.0.0.0:5558
web:
  https: 0.0.0.0:5556
  tlsCert: /tmp/tls.crt
  tlsKey: /tmp/tls.key

````

**Expected behavior**
Log in via Openshift works.
