### ISSUE TITLE
Expose notifications-controller metrics for monitoring

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj-labs/argocd-operator#1194]
**Is your feature request related to a problem? Please describe.**
The notifications-controller exposes a set of metrics that can be collected by prometheus and displayed in a grafana dashboard 
see https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/monitoring/

However, operator does not support this at this point.

**Describe the solution you'd like**
This can be achieved by creating the metrics service and service monitor for notifications controller by notifications is enabled.

**Describe alternatives you've considered**
Manually create the service and service monitor to expose the metrics to Prometheus.
```
apiVersion: v1
kind: Service
metadata:
 name: openshift-notification-controller
 namespace: openshift-gitops
 labels:
  app.kubernetes.io/name: openshift-gitops-notifications-controller
spec:
 selector:
  app.kubernetes.io/name: openshift-gitops-notifications-controller
 ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
    name: notification
```
```
   apiVersion: monitoring.coreos.com/v1
   kind: ServiceMonitor
   metadata:
   labels:
    release: prometheus-operator
    name: openshift-notification-controller
    namespace: openshift-gitops
    spec:
     endpoints:
      - port: notification
        scheme: http
        interval: 30s
     selector:
      matchLabels:
       app.kubernetes.io/name: openshift-gitops-notifications-controller
```
**Additional context**
see https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/monitoring/
