### ISSUE TITLE
configmap argocd-tls-certs-cm does not get populated with cr.spec.tls.initialCerts (v0.0.9)

### ISSUE THREAD

**Issue by ThomasVitt** [argoproj-labs/argocd-operator#122]
Hello, 
we want to insert a root CA certificate into argocd repo server in order to connect to our private Git Repos without the "insecure" option. According to the documentation (https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#tls-options) we are using the following spec: 

```yaml
spec:
  tls:
    initialCerts:
      root-ca.example.com: |-
        -----BEGIN CERTIFICATE-----
        MIIGbzCCBFegAwIBAgIQeM4J2V9oU5dCeqHWP/0dXzANBgkqhkiG9w0BAQsFADBt
        ...
        -----END CERTIFICATE-----
```

But the configmap "argocd-tls-certs-cm" contains no data after configuring the argocd object: 

```
[user@host ~]$ oc get cm argocd-tls-certs-cm
NAME                  DATA   AGE
argocd-tls-certs-cm   0      15m
```

Is it a bug or am I doing something wrong? 
The documentation says something about "The following properties are available for configuring the Grafana component.". But I think this is not for grafana, it's supposed to be for the repo-server, isn't it?

Thanks!
