### ISSUE TITLE
Support to specify an external Keycloak instance for SSO

### ISSUE THREAD

**Issue by tdkl** [argoproj-labs/argocd-operator#1238]
**Is your feature request related to a problem? Please describe.**
Going through the documentation for the ArgoCD Operator for an OpenShift deployment (https://argocd-operator.readthedocs.io/en/latest/usage/keycloak/openshift/), I wasn't able to find a specific ability to configure an external Keycloak instance to be used for OIDC. The configuration examples consist only of deploying a new and separate Keycloak instance, which isn't even persistent, which I found - interesting. If an organization already has a Keycloak (or other) instance, I don't find it really useful, to create one for every single implementation.

**Describe the solution you'd like**
Ability to configure an external Keycloak instance to be used for SSO login, like stated on regular ArgoCD documentation: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/, which isn't an operator deployed instance.

**Comment by bo0ts** [comment]
It's just like every other OIDC configuration. There is an example how to configure OIDC in your ArgoCD instance using the Operator: https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#oidc-config-example

A working example for Keycloak would be:

```
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
spec:
  oidcConfig: |
    name: Keycloak
    issuer: https://yourkeycloak.com/realms/yourrealm
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    public: true
```

`oidc.keycloak.clientSecret` needs to a be key in your `argocd-secret`.
