### ISSUE TITLE
Argocd failed to deploy (openshift - argocd 0.0.11)

### ISSUE THREAD

**Issue by Numblesix** [argoproj-labs/argocd-operator#124]
Hello,

we are using OpenShift 4.4 deploying ArgoCD using the Operator fails starting from 0.0.11 because of this:
```
  - dependents:
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: namespaced rule:{"verbs":["get"],"apiGroups":[""],"resources":["endpoints"]}
      status: NotSatisfied
      version: v1beta1
    group: ""
    kind: ServiceAccount
    message: Policy rule not satisfied for service account
    name: argocd-redis-ha
    status: PresentNotSatisfied
    version: v1
```

**Comment by Numblesix** [comment]
When checking the created Rolebindings i couldnt find the needed rolebinding 
```
➜  ~ oc get rolebindings
NAME                                            AGE
argocd-operator.v0.0.11-59498cfd4d-867fc7d49d   27m
argocd-operator.v0.0.11-5c4f7fbff8-6d77f974ff   27m
argocd-operator.v0.0.11-5c678c7876-5b6ccc9858   27m
argocd-operator.v0.0.11-79c565f65-65f799c44f    27m
argocd-operator.v0.0.11-7fb6c5c758-84475f47d    27m
system:deployers                                29m
system:image-builders                           29m
system:image-pullers                            29m
```
```
➜  ~ oc get rolebindings argocd-operator.v0.0.11-59498cfd4d-867fc7d49d -o yaml         
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
..
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-operator.v0.0.11-59498cfd4d
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
```
```
➜  ~ oc get rolebindings -o yaml argocd-operator.v0.0.11-5c4f7fbff8-6d77f974ff
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-operator.v0.0.11-5c4f7fbff8
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: argocd
```
```
➜  ~ oc get rolebindings -o yaml argocd-operator.v0.0.11-5c678c7876-5b6ccc9858                                             
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-operator.v0.0.11-5c678c7876
subjects:
- kind: ServiceAccount
  name: argocd-operator
  namespace: argocd
```
```
➜  ~ oc get rolebindings -o yaml argocd-operator.v0.0.11-79c565f65-65f799c44f                                             
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  ...
subjects:
- kind: ServiceAccount
  name: argocd-redis-ha-haproxy
  namespace: argocd
```
```
➜  ~ oc get rolebindings -o yaml argocd-operator.v0.0.11-7fb6c5c758-84475f47d                                            
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  ...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-operator.v0.0.11-7fb6c5c758
subjects:
- kind: ServiceAccount
  name: argocd-dex-server
  namespace: argocd
```
