### ISSUE TITLE
Add the ability to define content to be inserted into the argocd-cm configmap

### ISSUE THREAD

**Issue by tylerauerbeck** [argoproj-labs/argocd-operator#14]
A lot of additional configuration is handled within the `argocd-cm` configmap. Is there currently a way to define this as part of the request to spin up an ArgoCD instance? I don't see anything that pops out after a quick scan of the docs -- but is this currently possible with this operator? If not, is this something that this operator would want to do in the future? Happy to help contribute some of this if it would be accepted.

**Comment by jmckind** [comment]
Yes, I would like to provide the additional configuration through properties the ArgoCD Custom Resource. What sort of configuration is typically added? I would like to get an idea for what we should add as properties for handling the additional configuration. I assume things like the dex configuration, etc. 

If we look at part of the default example, it helps to illustrate what I have been thinking as far as organizing the various bits of configuration.

```
...
spec:
  image: argoproj/argocd
  version: v1.4.1
  controller:
    processors:
      operation: 10
      status: 20
  dex:
    image: quay.io/dexidp/dex
    version: v2.21.0
    oauth:
      enabled: false
  grafana:
    enabled: false
    host: example-argocd-grafana
    image: grafana/grafana
    size: 1
    version: 6.5.1
  import: {}
  ingress:
    annotations: {}
    enabled: false
    path: /
  prometheus:
    enabled: false
    host: example-argocd-prometheus
    size: 1
  redis:
    image: redis
    version: 5.0.3
  server:
    grpc:
      host: example-argocd-grpc
    host: example-argocd
    insecure: false
    service:
      type: ClusterIP
...
```

I feel that the implementation of some of that may be nieve in some areas and that is where I am interested in what sort of additional properties make sense.

I hope that helps to illustrate my thought process a bit in how I started everything. I am more than willing to accept any PRs or ideas you have to make the operator better and most importantly, useful!
