### ISSUE TITLE
RFE: Allow setting environment variables via operator

### ISSUE THREAD

**Issue by lhw** [argoproj-labs/argocd-operator#141]
For quite a few cases the option to supply environment variables via operator would be really useful. Especially for corporate proxies, but also secrets. 
I suggest something simple in the form of:
```yaml
environment:
  - name: VAR
    value: VAL
  - name: VAR2
    configmapRef:
      name: public
      key: key
  - name: VAR3
    secretKeyRef:
      name: secret
      key: key
```
Which, while verbose, should translate well to the actual deployments. I could imagine this as global for all deployments or service specific.
