### ISSUE TITLE
Appset controller deployment doesn't respect `.spec.image` & `.spec.version` fields in ArgoCD CR

### ISSUE THREAD

**Issue by svghadi** [argoproj-labs/argocd-operator#1517]
**Describe the bug**
Operator supports overriding default image for Argo CD components(server, repo-server, application-controller, applicationset-controller, notifications-controller) using `.spec.image` & `.spec.version` fields in ArgoCD CR. However, the `applicationset-controller` deployment doesn't respect this configuration. The image value is not reflected in the deployment. 

**To Reproduce**
Create ArgoCD CR
```yaml
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: example
spec:
  image: quay.io/argoproj/argocd
  version: v2.12.0
  applicationSet:
    enabled: true
```

**Expected behavior**
The `applicationset-controller` deployment should use image specified in `.spec.image` & `.spec.version fields` from ArgoCD CR. 

**Actual behavior**
The image in `applicationset-controller` deployment  point to default value set by the operator.

**Additional context**
ApplicationSet controller image can be configured using `.spec.applicationSet.image` & `.spec.applicationSet.version` fields of the `ArgoCD` CR. I believe, the operator should proritize the image configuration in following order
> `default value` < `.spec.image` < `.spec.applicationSet.image`
