### ISSUE TITLE
Support for custom labels and annotations to Server, repo, application set and application controller

### ISSUE THREAD

**Issue by enriqueav99** [argoproj-labs/argocd-operator#1530]
**Is your feature request related to a problem? Please describe.**
Hi! I need a feature that allows the addition of custom labels and annotations to pods deployed by the operator, specifically in the server, repos, application set and application controller components. This is required to enable direct metric scraping within the pod using Vector in my environment.

**Describe the solution you'd like**
Something like that:
```
spec:
  server:
    customPodLabels:
      custom: label
      asdf: server
    customPodAnnotations:
      asdf: server
      custom: annotation
  repo:
    customPodLabels:
      custom: label
      asdf: repo
    customPodAnnotations:
      asdf: repo
      custom: annotation
  controller:
    customPodLabels:
      custom: label
      asdf: controller
    customPodAnnotations:
      asdf: controller
      custom: annotation
  applicationSet:
    customPodLabels:
      custom: label
      asdf: applicationSet
    customPodAnnotations:
      asdf: applicationSet
      custom: annotation
```
**Additional context**
When I saw that the operator doesn´t support this feature, I found [this issue](https://github.com/argoproj-labs/argocd-operator/issues/637) and [this PR](https://github.com/argoproj-labs/argocd-operator/pull/1009).  Inspired by the code that @AlexanderThaller did in his branch, I started working on my own version, i have [a branch](https://github.com/enriqueav99/argocd-operator/tree/custom-labels-annotations) tfor testing and I accidentally opened [a PR](https://github.com/argoproj-labs/argocd-operator/pull/1529). I want to make another branch with diferent commits for a better review.
