### ISSUE TITLE
Security issue due to wide permissions

### ISSUE THREAD

**Issue by aelbarkani** [argoproj-labs/argocd-operator#154]
Hi,

I'm seeing that the controller has read access on all the resources of a cluster: https://github.com/argoproj-labs/argocd-operator/blob/master/deploy/olm-catalog/argocd-operator/0.0.13/argocd-operator.v0.0.13.clusterserviceversion.yaml#L520

Are these permissions necessary  even in namespaced installs ?

Regards

**Comment by aelbarkani** [comment]
and for multi-tenant clusters this security issue a very big impact

**Comment by jmckind** [comment]
Hi @aelbarkani. The operator was set up this way as per the guidance from the official Argo CD documentation.

https://argoproj.github.io/argo-cd/operator-manual/security/#cluster-rbac

Perhaps raising the issue upstream could get more insight into why Argo CD is designed this way.

That said, we can probably come up with a documented process that people who are concerned with the default behavior can follow to lock the operator down to a specific namespace or something similar.

**Comment by aelbarkani** [comment]
Thanks @jmckind. I see here though that there are two types of installations: standard and namespaced.

https://github.com/argoproj/argo-cd/tree/master/manifests
 
I think having the two options in the operator would be great (and more secure).

**Comment by Numblesix** [comment]
Oh yes :)) 

we had the same concern and opted out to install the operator for our application teams and went back to the normal install for them :) 

I see a huge use case for having multiple namespaced ArgoCD instances in bigger companies :)

**Comment by aelbarkani** [comment]
@Numblesix yes, we are considering the same here. For big companies having multi-tenant clusters in production it's a huge concern. So we are considering uninstalling the operator and get back to normal install.

**Comment by Numblesix** [comment]
> @Numblesix yes, we are considering the same here. For big companies having multi-tenant clusters in production it's a huge concern. So we are considering uninstalling the operator and get back to normal install.

You will still have to either fix a lot of rbac permissions or to blacklist basically everything in argocd which is on cluster-lvl

**Comment by aelbarkani** [comment]
@Numblesix thanks for the tip. did you use this manifest https://github.com/argoproj/argo-cd/blob/master/manifests/namespace-install.yaml ? I don't see any ClusterRole or ClusterRoleBinding there...

**Comment by chrisob** [comment]
@aelbarkani I had some success starting with that namespace-install.yaml, but I also had to make some significant changes before Argo CD was able to manage only namespace-scoped resources in other namespaces.

Regardless, here's some points on how I got it working:
- Create a rolebinding giving `argocd-application-controller` a namespaced admin role from your namespace
- Use [resource.inclusions](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion) to create a whitelist of resources which Argo CD is allowed to manage (this part sucks, but otherwise you get a bunch of errors that Argo CD failed to get some resource type).
- Create a [cluster in Argo CD](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters) which is namespaced:
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: namespaced-cluster
type: Opaque
stringData:
  config: '{"tlsClientConfig":{"insecure":false}}'
  name: in-cluster
  namespaces: my-namespace
  server: https://kubernetes.default.svc
```


If there's more interest in this, I can share a more complete code example, but for now I don't want to have to go through and sanitize any company references from the manifests :)

**Comment by aelbarkani** [comment]
thanks @chrisob ! will try that

**Comment by sbose78** [comment]
https://github.com/argoproj-labs/argocd-operator/blob/master/deploy/olm-catalog/argocd-operator/0.0.13/argocd-operator.v0.0.13.clusterserviceversion.yaml#L520

```
clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
        - nonResourceURLs:
          - '*'
          verbs:
          - get
          - list
        serviceAccountName: argocd-application-controller
```

This effectively enables `argocd-application-controller` to read all resources, but without being able to create/update, is this of any use?

I think, this rolebinding gives `argocd-application-controller` the powers it needs to be able to create/update objects. 

https://github.com/argoproj-labs/argocd-operator/blob/master/deploy/olm-catalog/argocd-operator/0.0.13/argocd-operator.v0.0.13.clusterserviceversion.yaml#L666 


In that case, maybe we could even remove the `clusterPermissions` ? Of course, that makes me wonder how argocd would watch cluster-scoped resources.
