### ISSUE TITLE
Supported argocd versions are unclear

### ISSUE THREAD

**Issue by bo0ts** [argoproj-labs/argocd-operator#1572]
**Describe the bug**
The operator installs a default version of argocd. It is not clear from the documentation if it is possible to also deploy other argocd versions with a given operator version. The argocd CRD has a version field, but the documentation is rudimentary.

**Expected behavior**
Clear documentation on which versions can be deployed with a given operator version (e.g. operator release 0.12.0, supports all argocd versions 0.12.X).

**Additional context**
There is a bugfix in a argocd minor release which I would like to deploy using the argocd-operator. Also the argocd-operator release cycle is much slower than the argocd release cycle and I would like to have an up-to-date argocd installation.

**Comment by svghadi** [comment]
Hi @bo0ts, yes, you can deploy other Argo CD versions by using  `.spec.image` & `.spec.version` fields ArgoCD CR

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: <your-argocd-instance>
spec:
  image: quay.io/argoproj/argocd
  version: v2.12.3
```

The supported versions are 
```
Operator 0.12.0 -> Argo CD 2.12.x
Operator 0.11.0 -> Argo CD 2.11.x
```

We are in the process of updating our documentation and automating our release process. We are hopeful that things will be better in the future.
