### ISSUE TITLE
ArgoCDExport image doesn't work with Argo CD v2.13.x artifacts

### ISSUE THREAD

**Issue by svghadi** [argoproj-labs/argocd-operator#1631]
**Describe the bug**
ArgoCDExport export fails to backup Argo CD when the image is built using v2.13.x artifacts. `build/util/Dockerfile` uses upstream Argo CD image for argocd-cli to back up Argo CD instances. However, with latest version, few things have changed which result into back up failure. 

**To Reproduce**
1. Update `build/util/Dockerfile` to point to latest Argo CD image
2. Build & push util image `UTIL_IMG=quay.io/<your-user>/argocd-operator-util:test make util-build util-push`
3. Reference new util image in `ArgoCDDefaultExportJobImage` & `ArgoCDDefaultExportJobVersion` in `common/defaults.go` file.
4. Run operator `make install run`
5. Create ArgoCD and ArgoCDExport resource
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExport
metadata:
  name: example-argocdexport
spec:
  argocd: example-argocd
```
6. Check export pod logs for error
```yaml
$ kubectl -n kuttl-test-measured-bluegill logs pod/example-argocdexport-rtrrd 
exporting argo-cd
creating argo-cd backup
time="2024-12-20T05:39:16Z" level=fatal msg="configmaps \"argocd-cmd-params-cm\" not found"
```

**Expected behavior**
The backup should happen without any failures. 

**Additional context**
For now, to unblock the release, Argo CD version in pinned to v2.12.3 in `argocd-operator-util` image.
