### ISSUE TITLE
Redis Pods Running with Higher Privileges in Namespace-Scoped Argo CD Instance

### ISSUE THREAD

**Issue by Mangaal** [argoproj-labs/argocd-operator#1662]
### Description

When installing a namespace-scoped Argo CD instance, the argocd-redis pods are assigned the nonroot-v2 SecurityContextConstraints (SCC) instead of the default restricted-v2 SCC. This results in the pods having higher privileges than expected.

This issue appears to originate from the Redis container image, which explicitly sets RunAsUser: 999, requiring nonroot-v2 SCC instead of the more restrictive restricted-v2 SCC. 

### Key Question
Is there a specific reason the Redis container must run as UID 999 instead of using a dynamically assigned UID?

**Security Concern: Elevated Privileges for Redis ServiceAccount**

In OpenShift, SecurityContextConstraints (SCCs) define the security policies under which pods operate.

**Expected SCC for namespace-scoped Argo CD instances**: restricted-v2 (enforces randomized UID allocation and strict privilege restrictions).

**Current SCC for Redis pods:** nonroot-v2 (allows running as a fixed UID, in this case, 999, which grants higher privileges).

This discrepancy raises potential security concerns, as unprivileged users may be able to deploy a pod using the argocd-redis ServiceAccount with elevated privileges.

**Steps to Reproduce**

**Install the OpenShift GitOps Operator using the default settings.
The OpenShift GitOps Operator only supports the AllNamespaces InstallMode, meaning the ArgoCD Custom Resource (CR) is available in all namespaces.**

```
$ oc get csv openshift-gitops -o yaml | yq '.spec.installModes'
[
  {
    "supported": false,
    "type": "OwnNamespace"
  },
  {
    "supported": false,
    "type": "SingleNamespace"
  },
  {
    "supported": false,
    "type": "MultiNamespace"
  },
  {
    "supported": true,
    "type": "AllNamespaces"
  }
]
```

**Create a new namespace and deploy an ArgoCD instance as an unprivileged user:**

```
$ oc whoami
manu
$ oc new-project manu
```

**Create an ArgoCD instance:**

```
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: my-user-instance
  namespace: manu
```

**Apply the resource:**

`$ oc apply -f ArgoCD.yaml`

**Check the ServiceAccounts created by the operator:**

```
$ oc get sa my-user-instance-argocd-redis my-user-instance-argocd-redis-ha -n manu
NAME                               SECRETS   AGE
my-user-instance-argocd-redis      0         125m
my-user-instance-argocd-redis-ha   0         125m
```

**Create a pod that uses the argocd-redis ServiceAccount:**

```
apiVersion: v1
kind: Pod
metadata:
  name: hellokube
spec:
  containers:
  - name: app-py
    image: quay.io/manue/hellopy:6
  securityContext:
    runAsUser: 1000
  serviceAccountName: my-user-instance-argocd-redis
```
**Apply the Pod resource:**

`$ oc apply -f pod.yaml`

**Verify that the process inside the pod is running with UID 1000 instead of a randomized UID:**

```
$ oc debug hellokube -- id 
uid=1000(1000) gid=0(root) groups=0(root)
```
