### ISSUE TITLE
Ability to provide a custom spec for repo-server

### ISSUE THREAD

**Issue by HumairAK** [argoproj-labs/argocd-operator#172]
As per  #155, making this into a new issue as the other one is labelled as a "question". 

I think it would be very useful to have the ability to provide a custom spec for repo-server (and possibly the other components) as described in the argocd docs [here](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/#adding-tools-via-volume-mounts). There are certain use cases where having a custom image is not enough. For example if you need to mount secrets to allow argocd the ability to decrypt manifests, you would not want to include these into a custom image.

**Comment by vassilvk** [comment]
As per my comment on #155, until the operator is extended to expose the spec of the repo-server, one can customize any spec generated by the operator with a [KubeMod](https://github.com/kubemod/kubemod) ModRule.

**Comment by mogsie** [comment]
I found a simple way to work around this, albeit a bit hackish.  I created an ArgoCD job that uses strategic merge to patch in the desired secrets.  The ArgoCD operator doesn't mind those extra mountpoints and volumes.  This allowed me to automatically boot up an ArgoCD *with* a GnuPG key for SopsSecretsGenerator, which then (when it rolled out) is able to decrypt the secrets it has.

The application applies following manifest.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: heal-argocd-operator
  name: argocd-repo-server
  namespace: stibodx-argo-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    spec:
      volumes:
        - name: gpg-secring
          secret:
            secretName: gpg-private-key
            defaultMode: 220
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: gpg-secring
              mountPath: /mnt/gpg-private-key
```

It's of course probably possible to use other types of patches; this was the first I reached for.  Ideally the secret name would include a hash (coming from kustomize), but I'd have to investigate how to pair a strategic patch like this with kustomize.

Hope this helps.
