### ISSUE TITLE
argocd-repo-server fails with "/dev/shm: no space left on device"

### ISSUE THREAD

**Issue by ASoldo** [argoproj-labs/argocd-operator#1754]
**Describe the bug**
We are running Argo CD via the Operator in an OpenShift environment.

- **Operator version**: `0.13.0`
- **Argo CD version**: `v2.13.1`

Despite configuring the `argocd-repo-server` to mount `/dev/shm` as an `emptyDir` with `medium: Memory` and a `sizeLimit` of `8Gi`, we continue to receive the following error during application sync:

Failed to write manifest: write /dev/shm/XXXXXX: no space left on device

We confirmed:

- `/dev/shm` is mounted correctly with 8Gi capacity and shows 0% usage (`df -h /dev/shm`)
- Inodes are not exhausted (`df -i /dev/shm`)
- `/tmp` is mounted and available as an alternative write location (`TMPDIR`, `HOME`, etc., are all set correctly)
- The repo-server logs show no crash; sync fails silently due to this error

It appears the GitOps engine is still using `/dev/shm` even when `TMPDIR` and alternative volumes are configured.

---

### To Reproduce

1. Install `argocd-operator` version `0.13.0` on OpenShift
2. Deploy an ArgoCD custom resource with the following relevant configuration:

```yaml
spec:
  repo:
    env:
      - name: TMPDIR
        value: /tmp/argocd-temp
      - name: HOME
        value: /tmp/argocd-temp
      - name: GNUPGHOME
        value: /tmp/argocd-temp/.gnupg
      - name: XDG_CACHE_HOME
        value: /tmp/argocd-temp/.cache
      - name: XDG_RUNTIME_DIR
        value: /tmp/argocd-temp/.runtime
      - name: ARGOCD_EXEC_TIMEOUT
        value: "600"
      - name: ARGOCD_SERVER_REPO_SERVER_TIMEOUT_SECONDS
        value: "300"
    volumeMounts:
      - mountPath: /dev/shm
        name: shm-volume
      - mountPath: /tmp/argocd-temp
        name: temp-volume
    volumes:
      - name: shm-volume
        emptyDir:
          medium: Memory
          sizeLimit: 8Gi
      - name: temp-volume
        emptyDir:
          sizeLimit: 10Gi
```

**Expected behavior**
Sync a moderately large application using Helm or Kustomize
See the following error:
Failed to write manifest: write /dev/shm/XXXXXX: no space left on device

Not sure what to do here since this is the first time i encounter this issue.
