### ISSUE TITLE
argocd-dex-server Deployment's init container does not use image variable

### ISSUE THREAD

**Issue by Obirah** [argoproj-labs/argocd-operator#211]
When specifying an image in the `ArgoCD` resource as documented [here](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#image), the init container `copyutil` of the `argocd-dex-server` deployment does not use the specified image (contrary to all the other deployments).

**Comment by bigkevmcd** [comment]
Hello, thanks for the report, can you confirm which version of the operator, and how you're configuring the image?

**Comment by Obirah** [comment]
Sorry, could've said that from the beginning. It's the ArgoCD operator 0.0.14 installed via OLM on OpenShift 4.6 and my configuration is looking like this:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: my-argo-cd
spec:
  dex:
    openShiftOAuth: true
  image: redacted.company.docker.mirror/argoproj/argocd
  rbac:
    policy: |
      g, cluster-admin, role:admin
  redis:
    image: redacted.company.docker.mirror/redis
  server:
    autoscale:
      enabled: true
    ha:
      enable: true
    host: my-argocd.apps.my-ocp-cluster.my-company.com
    ingress:
      enabled: false
    insecure: true
    route:
      enabled: true
  usersAnonymousEnabled: false
```

I have already seen that the `dex` section of the CR has an `image` field for the dex image itself, but this obviously doesn't have anything to do with the init container.
