### ISSUE TITLE
Unable to create project on OpenShift with RBAC

### ISSUE THREAD

**Issue by arve0** [argoproj-labs/argocd-operator#213]
Hi 👋 I've followed the [example in the documentation|https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#dex-openshift-oauth-example] for RBAC on OpenShift.

Login is successful. User-info request returns:
```json
{
  "loggedIn":true,
  "username":"admin-extase",
  "iss":"https://argocd-server.apps.ocp-lab2.regsys.brreg.no/api/dex",
  "groups":["OCP-admins","system:authenticated","system:authenticated:oauth"]
}
```

The group _OCP-admins_ has a ClusterRoleBinding to `cluster-admin`:
```sh
> oc get clusterrolebinding cluster-admin-0 -o yaml | yq r - subjects
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: OCP-admins
```

Relevant ArgoCD configuration is:
```yaml
dex:
  image: quay.io/redhat-cop/dex
  openShiftOAuth: true
  version: v2.22.0-openshift
rbac:
  defaultPolicy: role:readonly
  policy: |
    g, system:cluster-admin, role:admin
  scopes: '[groups]'
```

**Note**: I believe the documentation is wrong, with plural `system:cluster-admins`, though I've tried both.

When creating a new project in web-ui, the response has status 403 with body:
```json
{
  "error":"permission denied: projects, create, extase, sub: CiQ2N2ZlMWFmZi03YmUxLTQzYTgtODI2OC00MDBmY2QwMDJhYjMSCW9wZW5zaGlmdA, iat: 2020-12-07T14:04:56Z",
  "code":7,
  "message":"permission denied: projects, create, extase, sub: CiQ2N2ZlMWFmZi03YmUxLTQzYTgtODI2OC00MDBmY2QwMDJhYjMSCW9wZW5zaGlmdA, iat: 2020-12-07T14:04:56Z"
}
```

Any ideas what I'm doing wrong?
