### ISSUE TITLE
Ingress annotations getting ignored

### ISSUE THREAD

**Issue by Unb9rn** [argoproj-labs/argocd-operator#24]
While trying to configure ArgoCD resource with this operator I've got an problem when "annotations" for ingress would be ignored and resulting ingress gets "nginx" ingress class.
Maybe I'm doing something wrong(there is no example how this annotation should be written)
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    env: devenv
spec:
  ingress:
    enabled: true
    path: /
    annotations:
       kubernetes.io/ingress.class: nginx-yandex-main
```
