### ISSUE TITLE
Routes in OKD deployments with their own SSL termination do not work

### ISSUE THREAD

**Issue by bo0ts** [argoproj-labs/argocd-operator#299]
**Describe the bug**

Routes in OKD deployments with their own SSL termination do not work and end in `ERR_TOO_MANY_REDIRECTS`. This is caused by argocd redirecting back to https when receiving http traffic. A supposed fix should be `spec.server.insecure: true`, this create the route correctly with `termination: edge`, but fails to add `--insecure` to argocd server.

**To Reproduce**
Create argo cd instance with:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  server:
    route:
      enabled: true
      tls:
        termination: edge
```

**Expected behavior**

`spec.server.insecure: true` should create a working route or reencryption should be enabled for the route.

**Comment by iam-veeramalla** [comment]
@bo0ts is there a specific reason why you are not using passthrough/redirect ? 

Thanks for correctly pointing out issue with Edge termination.

**Comment by iam-veeramalla** [comment]
However, this does not work.
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  server:
    route:
      enabled: true
      tls:
        termination: edge
```
