### ISSUE TITLE
Annotations on ingress object are not working.

### ISSUE THREAD

**Issue by crmarques** [argoproj-labs/argocd-operator#317]
**Describe the bug**
Annotations on ingress object are not working.

**To Reproduce**
Create an argocd instance with ingress annotations:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  server:
    host: argocd-example
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
```
Get Ingress definition:

```
># kubectl get ingress argocd-server -n argocd -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  ...
spec:
  ...
```

**Expected behavior**

An Ingress object with the specified annotations:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  ...
spec:
  ...
```

** Version **
v0.0.14
