### ISSUE TITLE
Define `spec.url` in Configmap

### ISSUE THREAD

**Issue by rv-silva** [argoproj-labs/argocd-operator#335]
When deploying Ingress externally to ArgoCD operator (GKE with Traefik), altering `spec.url` in Operator CR will not cause `argocd-cm` to change. It is a problem when using DEX.

1) Regular approach:
```yaml
data:
  url: https://example-argocd-server
``` 

It will keep the default value of:
```yaml
url: https://argocd-server
```

2) https://github.com/argoproj-labs/argocd-operator/issues/103 did not work:
```yaml
spec:
  server:
    route:
      enabled: true
    host: my.domain.app
```
```yaml
kubectl get configmap argocd-cm -n argocd -o yaml      
apiVersion: v1
data:
  url: https://argocd-server
```

3) https://github.com/argoproj-labs/argocd-operator/pull/236 also did not work:
```yaml
spec:
  server:
    host: my.domain.app
```
```yaml
kubectl get configmap argocd-cm -n argocd -o yaml                                        
apiVersion: v1
data:
  url: https://argocd-server
```

4) Only (but not viable) way found makes ArgoCD Operator to create additional Ingress:
```yaml
spec:
  server:
    grpc:
      ingress:
        enabled: true
    ingress:
      enabled: true
    insecure: true
    host: my.domain.app
```
```yaml
kubectl get configmap argocd-cm -n argocd -o yaml                                        
apiVersion: v1
data:
  url: https://my.domain.app
```
 
**Please, is not possible to add a direct way to set URL value to any defined in CR `spec.url`?**
