### ISSUE TITLE
Something is wrong with password passing

### ISSUE THREAD

**Issue by Unb9rn** [argoproj-labs/argocd-operator#36]
I am trying to create a new instance with this config:
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-main
  namespace: argocd
  labels:
    env: prod
spec:
  image: argoproj/argocd
  version: v1.4.2
  ha:
    enabled: false
  server:
    autoscale:
      enabled: false
    grpc:
      host: grpcsome.domain
      ingress: true
    host: some.domain
    ingress: true
    insecure: true
    service:
      type: ClusterIP
  redis:
    image: redis
    resources: {}
    version: 5-alpine
  statusBadgeEnabled: true
  usersAnonymousEnabled: false
  grafana:
    enabled: false
  prometheus:
    enabled: false
```
It creates everything and there is a pod named `argocd-main-server-765b55b765-pv6w7`
When I try to use it as a password to "admin" account it fails to log me in.
I even tried to patch a secret with password with something as simple as 12345 in bcrypt hash, yet it won't work for some reason. I think it may be related to #29 issue as OLM automatically installs 0.0.6... Maybe it's time to create bet branch for semi-stable versions? =)
