### ISSUE TITLE
Ability to utilize secret value to populate Dex clientSecret

### ISSUE THREAD

**Issue by Kampe** [argoproj-labs/argocd-operator#375]
Is there a way to utilize a secret to populate the value for clientSecret within the dex config options?  There doesn't seem to be a way to include environment variables on a per component basis?

**Comment by iam-veeramalla** [comment]
Hi @Kampe Thanks for raising issue with us.

Can you please provide more information on what exactly you are trying to achieve and steps to reproduce.

**Comment by Kampe** [comment]
Sure!

Currently, this is seemingly the amount of config we can use to set up our client  for DEX:

```
      dex:
        config: |
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                redirectURI: https://localhost:8080/api/dex/callback
                clientID: 85409387507sd67f6
                clientSecret: $dex.github.clientSecret
                orgs:
                - name: org-name
             ```

However, I can't use my own secret to populate these values, both clientID and clientSecret within the DEX configuration block.  This would be wildly useful to everyone to have available.  Ideally they are NOT attached to the $dex.github object and can be their very own secrets as I do not want to touch argocd internal secrets to get to my own personal env vars.

**Comment by iam-veeramalla** [comment]
Hi @Kampe , You can also use your own kubernetes secrets.
```
clientSecret: $dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
```

Is this what you are looking for ?

**Comment by brandon-piner-aruba** [comment]
@iam-veeramalla please can you elaborate on this because the documentation still seems to be missing information. 

I have created a secret in the same namespace as argocd.
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-secret
  namespace: argocd
data:
  clientSecret: 1ce6dfe5134cd281831b2ab648e9caf5e3d36027
type: Opaque
```

Then what should the config be?

```yaml
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 0000000000478c81c342
          clientSecret: $argocd-github-secret.clientSecret # or $argocd-github-secret:clientSecret
```

**Comment by RafPe** [comment]
@brandon-piner-aruba I have come across the same problem. For me, it did not work when I put the value in custom secret. 

However with some tinkering :) I got it to run when I put the value `dex.github.clientSecret` into secret called `argocd-secret`. 

All other attempts of using secret created by me with the name `sso` , failed with the same message of `level=warning msg="config referenced '$sso:dex.github.clientSecret', but the key does not exist in secret"`

Could you maybe give some hint @iam-veeramalla on using custom secrets instead ?

**Comment by joshperry** [comment]
We use bank-vaults w/transit so it's easiest for us to use env vars. I found that if you put `$ENV_VAR_NAME` in a value, you'll see an error, but the value is passed through to the config file and [dex supports env vars](https://github.com/dexidp/dex/issues/1158) in its config.

We set the `env:` value of the dex pod (helm) to have encrypted values, bankvaults decrypts them, and dex plucks them out of the env.

```
dex-server time="2023-09-25T20:01:50Z" level=warning msg="config referenced '$GOOGLE_OIDC_CLIENT_SECRET', but key does not exist in secret"
```

**Comment by zebesh** [comment]
@joshperry Can you show how you did it?

**Comment by saulrobe** [comment]
What @RafPe showed worked for me.
Here is the docs that should help more:
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets

Basically a couple of things to note:
- If you are making a secret make sure to include a label in the metadata for `app.kubernetes.io/part-of: argocd`
- If your secret is not named "argocd-secret" then to reference it in the configmap your syntax needs to be `$<k8s_secret_name>:<a_key_in_that_k8s_secret>`

For example with the secret:

``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-client
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
stringData:
  clientSecret: 'whatevertheactualsecretis'
```

A [helm chart](https://artifacthub.io/packages/helm/argo/argo-cd) with values similar to the following will use the secret:

``` yaml
# ... other values ...
configs:
  cm:
    dex.config: |
      connectors:
        - type: oidc
          id: oidc
          name: OIDC
          config:
            issuer: https://issuer_address.com/
            clientID: 'whatever_the_client_id_is'
            clientSecret: $argocd-oidc-client:clientSecret
# ... other values ...
```

Note, in the example the secret is using stringData, but if you use the normal data field remember to base64 encode the value.
