### ISSUE TITLE
"groups" Parameter within dex.config for the OpenShift connector to restrict logins

### ISSUE THREAD

**Issue by maik-d** [argoproj-labs/argocd-operator#391]
Hello,

I was wondering whether a feature could be implemented which allows setting the "group" parameter as well as several groups within the ArgoCD operator dex config in order to restrict the overall login to the related ArgoCD instance, by also keeping the currently dynamic "openShiftOAuth: true" setting.
I also have to mention that this can already be done by using the spec.dex.config parameter within the ArgoCD CRD manifest - _however this approach is quite static_, as writing information to spec.dex.config disables the automatic configuration that has been set via spec.dex.openShiftOAuth.

To give a specific example, I could append the following configuration to spec.dex.config within my ArgoCD CRD:

```
config: |
  connectors:
  - config:
        id: openshift
        name: OpenShift
        type: openshift
        **groups:
          - <OpenShift group name allowed to log in>**
      clientID: <argocd dex server ca>
      clientSecret: <token of argocd dex server ca>
      insecureCA: <true/false>
      issuer: https://kubernetes.default.svc
      redirectURL: <URL to redirect to>
```

But this essentially disables the usage of such configuration in its own GitOps approach, as the value of the clientSecret should be dynamic and not statically written into the config. The current dynamic implementation seems to be at exactly this place:

https://github.com/argoproj-labs/argocd-operator/blob/master/pkg/controller/argocd/util.go#L401

An example of how the configuration should be written in order to restrict access to ArgoCD can be obtained from here:

https://cloud.redhat.com/blog/openshift-authentication-integration-with-argocd (Chapter "Utilize OpenShift Groups to Restrict Access")

Please do not hesistate to correct me if I am missing something and this is already possible in some way.

Best regards!

**Comment by iam-veeramalla** [comment]
Hi Maik, Thanks for raising issue with us.

If I can understand your request correctly, You are looking for a way to update the group policy(restrict or privilege a specific group with permissions on Argo CD). 

If that is true, you can already do it using the RBAC field in the Argo CD CR. Below is the example for reference.
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: rbac
spec:
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
```

You can read more about it at [RBAC options](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#rbac-options)  and [RBAC Examples](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#rbac-example)
 
 Does this help ?

**Comment by maik-d** [comment]
Hi,

Thanks for the fast reply!

I do not want to set the RBAC policy but instead aim to only allow specific groups to login to ArgoCD at all.
This can be achieved with the groups parameter under a specific connector (as seen in my example from the initial post).
The issue is, that I can - as of now - only set this via the spec.dex.config portion of the ArgoCD operator instances manifest.
This basically disables the auto configuration of the OpenShift dex connector, which has been set by changing the value of the parameter openShiftOAuth to true.
Long story short, I am asking whether a feature can be added to the operator, which allows to directly mention user groups which should be denied from logging into a given ArgoCD instance, but also still allow the automatic configuration of the openshift dex connector.

Regards

**Comment by iam-veeramalla** [comment]
It makes much sense now, Thanks for the detailed explanation. 

This looks like a sophisticated request :). This is what we can do currently, make any default logged in user a readonly user and allow only specific groups to perform specific actions.

```
**rbac**:
    policy: |
      g, system:cluster-admins, role:admin
      g, admins, role:admin
      g, developer, role:developer
      g, marketing, role:marketing
```
**rbac.defaultPolicy**: 'role:readonly' (This will ensure by default every logged in user is a readonly user).

The overall Argo CD CR would look something like this.
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    route:
      enabled: true
  dex:
    image: ghcr.io/dexidp/dex
    openShiftOAuth: true
    version: v2.28.0
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      g, admins, role:admin
      g, developer, role:developer
      g, marketing, role:marketing
    scopes: '[groups]'
```
