### ISSUE TITLE
RBAC issues with 0.0.5

### ISSUE THREAD

**Issue by Unb9rn** [argoproj-labs/argocd-operator#40]
I've tried setting up ArgoCD with this operator (both installed with OLM and manually)
And now when I create an Application I am getting this error:
`secrets is forbidden: User "system:serviceaccount:argocd:argocd-application-controller" cannot create resource "secrets" in API group "" in the namespace "clickhouse"`

Application yaml:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@domain.com:some/path/gitops.git
    targetRevision: HEAD
    path: service/overlays/production/clickhouse
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    validate: true
```
