### ISSUE TITLE
Changing host does not update ingress

### ISSUE THREAD

**Issue by ghost** [argoproj-labs/argocd-operator#558]
**Describe the bug**
When setting up an `ArgoCd`, and later changing the host the ingress will not be updated with the new host information.

**To Reproduce**
Do a kubectl apply on something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  server:
    ingress:
      enabled: true
```

followed by a kubectl apply on something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  server:
    host: foo.bar

    ingress:
      enabled: true
```

then the host will still be set to the default value when describing the ingress

**Expected behavior**
That the ingress will be updated with the new host

**Comment by renemifsud** [comment]
Is there any news on this please? Its a bit counter intuitive to have an operator but its still needed to alter the ingress directly after installation.

**Comment by Elyytscha** [comment]
@svghadi i think thats an issue that should be prioritized. we run into the same issue, additionally its possible that this behavior is at more places.

we deleted the ingress, so it got recreated with the new host, but it did not update other things related to that

like
```yaml
  sso:
    dex:
      config: |
        connectors:
        - type: oidc
          id: keycloak
          name: keycloak
          config:
            issuer: https://sso.example.com/realms/MASTER
            redirectURI: https://argocd.example.com/api/dex/callback
            clientID: argocd.example.com
```

we changed clientID and redirectURI and the operator did not update those after we recreated the ingress (with deleting it and let the operator recreate it), so we couldn't login.

so i think the operator has in general issues with updating values when they get changed, imo we should look into that and maybe rework the update mechanism in general.

we ended up in just deleting the argocd custom resource itself and re applied it.
