### ISSUE TITLE
ArgoCD Export to GCP backend fails - gcloud not in PATH

### ISSUE THREAD

**Issue by ken-ie** [argoproj-labs/argocd-operator#596]
**Describe the bug**
When the export job to a gcp backend is created, the container crashes with the following error:
```
$ kubectl logs -n argocd-production argocd-export-gcp-m7qc8 -f
exporting argo-cd
creating argo-cd backup
encrypting argo-cd backup
pushing argo-cd backup to gcp
/usr/local/bin/argocd-operator-util: line 87: gcloud: command not found
```

**To Reproduce**
Set up an export to GCP:
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExport
metadata:
  name: argocd-export-gcp
  namespace: argocd-production
  labels:
    test: version-1
spec:
  argocd: argocd
  storage:
    backend: gcp
    secretName: argocd-export-gcp-secret
```

The the export is created, the above error occurs.

Checking the pod, I find the following image:
`quay.io/argoprojlabs/argocd-operator-util@sha256:411388a09cbba0502639e0190a68d82ae2d7716863e35b2af7322384b2c6af48`

Run that image, looking for gcloud command. Gcloud is installed, but not in the `PATH`

```
docker run --rm -ti --name tmp --entrypoint bash quay.io/argoprojlabs/argocd-operator-util@sha256:411388a09cbba0502639e0190a68d82ae2d7716863e35b2af7322384b2c6af48

argocd@d9946953d046:~$ which gcloud
argocd@d9946953d046:~$ cd /
argocd@d9946953d046:/$ find -name gcloud
find: './var/cache/apt/archives/partial': Permission denied
find: './var/cache/ldconfig': Permission denied
find: './proc/tty/driver': Permission denied
./home/argocd/google-cloud-sdk/lib/googlecloudsdk/googledata/devsite/site-cloud/en/sdk/gcloud
./home/argocd/google-cloud-sdk/platform/gsutil_py2/gslib/vendored/oauth2client/tests/data/gcloud
./home/argocd/google-cloud-sdk/bin/gcloud
./home/argocd/google-cloud-sdk/.install/.backup/lib/googlecloudsdk/googledata/devsite/site-cloud/en/sdk/gcloud
./home/argocd/google-cloud-sdk/.install/.backup/bin/gcloud
find: './etc/ssl/private': Permission denied
find: './root': Permission denied

argocd@d9946953d046:/$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Need to include add `./home/argocd/google-cloud-sdk/bin/` to the `PATH`
