### ISSUE TITLE
ability to set annotations+labels on pods created by argocd

### ISSUE THREAD

**Issue by Morriz** [argoproj-labs/argocd-operator#637]
**Is your feature request related to a problem? Please describe.**
Hi, we need to set annotations on any pods running on our cluster, but I can't find the option to do so on pods deployed by argo.

**Describe the solution you'd like**
Something like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
...
controller:
  podAnnotations:
    some: anno
  labels:
    some: label
...
server:
  podAnnotations:
    ana: da
```
