### ISSUE TITLE
Cluster-scoped vs Namespace-scoped information in docs

### ISSUE THREAD

**Issue by nccurry** [argoproj-labs/argocd-operator#665]
**Is your feature request related to a problem? Please describe.**

ArgoCD can be cluster or namespace scoped. 
It would be good to have information on how to control this behavior in the ArgoCD operator in the documentation. 

**Describe the solution you'd like**

Do X  for namespace-scoped ArgoCD via the operator

Do Y for cluster-scoped ArgoCD via the operator

**Describe alternatives you've considered**

**Additional context**

**Comment by nccurry** [comment]
Issue https://github.com/argoproj-labs/argocd-operator/issues/385 implies the solution is to manually add a list of namespaces ArgoCD is allowed to manage to the Subscription in an environment variable ARGOCD_CLUSTER_CONFIG_NAMESPACES.


i.e.
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd
  namespace: argocd
spec:
  channel: alpha
  name: argocd-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: argocd
```
