### ISSUE TITLE
Wildcards in ArgoCD sourceNamespaces prevent resource creation

### ISSUE THREAD

**Issue by deas** [argoproj-labs/argocd-operator#849]
**Describe the bug**

Wildcards in `ArgoCD` `sourceNamespaces` prevent resource creation.

**To Reproduce**

1. Follow [Applications in any namespace](https://argocd-operator.readthedocs.io/en/latest/usage/apps-in-any-namespace/#using-application-namespaces) using

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  sourceNamespaces:
    - "*"
 ``` 
2. Apply the manifest to a cluster running argocd-operator v0.5.0
3. Actual resources don't get created

**Expected behavior**
Actual resources being created. Full access to all namespaces.

**Screenshots**
n/a

**Additional context**
Using v0.5.0
