### ISSUE TITLE
Webhooks secret not configurable

### ISSUE THREAD

**Issue by paolocarta** [argoproj-labs/argocd-operator#93]
I had a look at the reference docs and I did not find a way to configure the git webhooks secret in the ArgoCD custom resource.

I think it would be great being able to do that.

**Comment by jmckind** [comment]
Hi @paolocarta, thank you for your feedback and interest in the operator.

To be clear, you are referring to the webhook secrets in the `argocd-secret` Secret?

``` yaml
  webhook.github.secret: shhhh! it's a github secret
  # gitlab webhook secret
  webhook.gitlab.secret: shhhh! it's a gitlab secret
  # bitbucket webhook secret
  webhook.bitbucket.uuid: your-bitbucket-uuid
  # bitbucket server webhook secret
  webhook.bitbucketserver.secret: shhhh! it's a bitbucket server secret
  # gogs server webhook secret
  webhook.gogs.secret: shhhh! it's a gogs server secret
```
